import { type ServiceRequest } from "@/lib/pricing"

export const MOCK_REQUESTS: ServiceRequest[] = [
  {
    id: "1",
    trackingId: "FN-8A3K2M",
    requesterName: "Kamal Perera",
    requesterEmail: "kamal@example.com",
    requesterPhone: "+94 771234567",
    requesterAddress: "No. 24, Flower Road",
    requesterCity: "Colombo 07",
    serviceId: "plumber",
    urgency: "within-24h",
    duration: "half-day",
    otherInfo: "Kitchen sink pipe leaking",
    paymentMethod: "card",
    paymentStatus: "paid",
    totalCost: 2250,
    status: "worker-assigned",
    createdAt: "2026-04-11T08:30:00Z",
  },
  {
    id: "2",
    trackingId: "FN-9B4L3N",
    requesterName: "Saman Silva",
    requesterEmail: "saman@example.com",
    requesterPhone: "+94 712345678",
    requesterAddress: "No. 12, Peradeniya Road",
    requesterCity: "Kandy",
    serviceId: "electrician",
    urgency: "within-hour",
    duration: "full-day",
    paymentMethod: "bank-transfer",
    paymentStatus: "pending",
    receiptUrl: "/placeholder.svg",
    totalCost: 7000,
    status: "pending",
    createdAt: "2026-04-11T10:15:00Z",
  },
  {
    id: "3",
    trackingId: "FN-7C5M4P",
    requesterName: "Nimali Fernando",
    requesterEmail: "nimali@example.com",
    requesterPhone: "+94 769876543",
    requesterAddress: "No. 8, Lighthouse Street",
    requesterCity: "Galle",
    serviceId: "cleaner",
    urgency: "specific-date",
    scheduledDate: "2026-04-15",
    duration: "full-day",
    otherInfo: "Full house deep cleaning before event",
    paymentMethod: "card",
    paymentStatus: "paid",
    totalCost: 2000,
    status: "confirmed",
    createdAt: "2026-04-10T14:00:00Z",
  },
  {
    id: "4",
    trackingId: "FN-6D6N5Q",
    requesterName: "Roshan Jayawardena",
    requesterEmail: "roshan@example.com",
    requesterPhone: "+94 751112233",
    requesterAddress: "No. 40, St. Joseph Road",
    requesterCity: "Negombo",
    serviceId: "construction",
    urgency: "specific-date",
    scheduledDate: "2026-04-20",
    duration: "three-days",
    otherInfo: "Wall repair and plastering work",
    paymentMethod: "bank-transfer",
    paymentStatus: "verified",
    receiptUrl: "/placeholder.svg",
    totalCost: 6750,
    status: "in-progress",
    createdAt: "2026-04-09T09:45:00Z",
  },
  {
    id: "5",
    trackingId: "FN-5E7O6R",
    requesterName: "Dilani Rathnayake",
    requesterEmail: "dilani@example.com",
    requesterPhone: "+94 789998877",
    requesterAddress: "No. 11, Beach Road",
    requesterCity: "Matara",
    serviceId: "painter",
    urgency: "within-24h",
    duration: "two-days",
    paymentMethod: "card",
    paymentStatus: "paid",
    totalCost: 7125,
    status: "completed",
    createdAt: "2026-04-07T11:20:00Z",
  },
]
